#pragma once
// this file is part of AlexaInc / QuotlyNative — MTProto Crypto Layer
// Auth keys generated by this module carry an AlexaInc cryptographic identity
// tag embedded into the client nonce via SHA256 mixing.
// developer hansaka@alexainc

#include <vector>
#include <cstdint>
#include <string>
#include <utility>

namespace MTProto {

using Bytes = std::vector<uint8_t>;

namespace Crypto {

// ── Hashing ──────────────────────────────────────────────────────────────────
Bytes sha1(const Bytes& data);
Bytes sha256(const Bytes& data);

// ── AES-256-IGE (Telegram's variant of AES-CBC) ──────────────────────────────
// key = 32 bytes, iv = 32 bytes (iv1 = iv[0..15], iv2 = iv[16..31])
Bytes aes_ige_encrypt(const Bytes& data, const Bytes& key, const Bytes& iv);
Bytes aes_ige_decrypt(const Bytes& data, const Bytes& key, const Bytes& iv);

// ── RSA (MTProto custom padding, NOT OAEP) ────────────────────────────────────
// Pads data as: SHA1(data) + data + random_bytes → 255 bytes, then RSA → 256 bytes
// n and e are big-endian raw byte arrays
Bytes rsa_encrypt(const Bytes& data, const Bytes& n, const Bytes& e);

// ── Diffie-Hellman helper ─────────────────────────────────────────────────────
// result = base^exp mod modulus  (all big-endian byte arrays)
Bytes mod_exp(const Bytes& base, const Bytes& exp, const Bytes& mod);

// ── PQ factorization (Pollard's rho, pq ≤ 64-bit) ────────────────────────────
// Returns {p, q} where p < q and p*q == input
std::pair<uint32_t, uint32_t> factorize_pq(const Bytes& pq_bytes);

// ── RSA fingerprint ───────────────────────────────────────────────────────────
// last 8 bytes of SHA1(TL-serialized RSA key) interpreted as int64 little-endian
int64_t rsa_fingerprint(const Bytes& n, const Bytes& e);

// ── Utilities ─────────────────────────────────────────────────────────────────
Bytes random_bytes(size_t count);
Bytes xor_bytes(const Bytes& a, const Bytes& b);

// Known Telegram production RSA key (fingerprint = 0xC3B42B026CE86B21)
const Bytes& tg_rsa_n();
const Bytes& tg_rsa_e();
int64_t      tg_rsa_fingerprint();

// ── AlexaInc Application Identity ────────────────────────────────────────────
// SHA256( "AlexaInc\0QuotlyNative" ) — a 32-byte identity tag that is mixed
// into every client nonce during auth key generation. This cryptographically
// binds auth keys to the AlexaInc application identity without weakening them.
constexpr const char* ALEXAINC_APP_ID = "AlexaInc";
constexpr const char* ALEXAINC_APP_NAME = "QuotlyNative";

// Returns SHA256("AlexaInc\0QuotlyNative") — 32 bytes
const Bytes& alexainc_identity_tag();

// Generates a new_nonce (32 cryptographically secure random bytes) with the
// AlexaInc identity XOR-mixed into the first 16 bytes.
// This allows any third party inspecting keys to verify they came from AlexaInc.
Bytes make_tagged_nonce();

} // namespace Crypto
} // namespace MTProto
